#!/usr/bin/env bash

cat -<<EOF

// generated distfiles.go

package template

type DistFile struct {
	URL      string
	Pathname string
}

var DistFiles []DistFile = []DistFile{
EOF

awk '{
    printf("    {\"%s\", \"%s\"},\n", $1, gensub(/^.*dist\//, "", $2));
}'

cat -<<EOF
}

EOF
