#!/usr/bin/env bash

name=keymaster

echo adding $name CA to debian initrd.gz

fail () {
    echo >&2 $(basename $0): "$@"
    exit 1
}

target_of () {
    ls -l $1 | awk '{print $(NF)}'
}

to_crt() {
    local name=$1
    printf "%s.crt" ${name%.*}
}

relink() {
    rm $1
    ln -s $(basename $2) $1
}
key=/etc/ssl/${name}.pem

workdir=template/certs/debian
certsdir=$workdir/etc/ssl/certs
distdir=template/dist/debian
initdir=template/certs
rm -rf $workdir
rm -rf $initdir/initrd*
mkdir -p $certsdir
awk <$key >$certsdir/${name}_root.pem '{print} /---END CERTIFICATE---/{exit}'
awk <$key >$certsdir/${name}_intermediate.pem -v found=0 '{if (found) print} /---END CERTIFICATE/{found=1}'
case $(uname) in
    OpenBSD)
	( cd $certsdir; openssl certhash . )
	for pem in $(find $certsdir -type f -name '*.pem'); do
	    mv $pem $(to_crt $pem)
	done
	for link in $(find $certsdir -type l); do 
	    tgt=$(target_of $link)
	    #echo link=$link target=$tgt renamed=$(to_crt $tgt)
	    relink $link $(to_crt $tgt)
	done
	for initrd in $(find $distdir -name initrd.gz); do
	    cp $initrd $initdir/initrd.gz
	    rm -f $initdir/initrd
	    gunzip $initdir/initrd.gz
	    (cd $workdir; find . -not -type d | cpio -v -H sv4cpio -o -A -F ../initrd)
	    gzip $initdir/initrd
	    rm -f $initrd.keymaster
	    mv $initdir/initrd.gz $initrd.keymaster
	done
    ;;
    *) fail "unsupported OS";;
esac
#cpio -F template/certs/initrd -it
