#!/bin/sh

set -ueo pipefail

os=$1
major=$2
minor=${3:-}
patch=${4:-}

htdocs=template

openbsd_mirror=mirrors.mit.edu
openbsd_version="${major}.${minor}"
openbsd_arch=amd64

debian_mirror=ftp.us.debian.org
debian_version=${major}
debian_arch=amd64

alpine_mirror=dl-cdn.alpinelinux.org
alpine_arch=x86_64

openbsd_url() {
  printf "https://%s/pub/OpenBSD/%s/%s/" ${openbsd_mirror} ${openbsd_version} ${openbsd_arch}
}

debian_url() {
  printf "http://%s/debian/dists/%s/main/installer-%s/current/images/netboot/debian-installer/%s/" ${debian_mirror} ${debian_version} ${debian_arch} ${debian_arch}
}

alpine_dir() {
  printf "alpine/v%s.%s/releases/%s" ${major} ${minor} ${alpine_arch}
}

alpine_file() {
  printf "alpine-netboot-%s.%s.%s-%s.tar.gz" ${major} ${minor} ${patch} ${alpine_arch}
}

alpine_url() {
    printf "https://%s/%s/%s" ${alpine_mirror} $(alpine_dir) $(alpine_file)
}

case $os in 
    openbsd) ( cd $htdocs; wget --no-clobber --no-host-directories --no-parent -r $(openbsd_url); );;
    debian) ( cd $htdocs; wget --no-clobber --no-host-directories --no-parent -r $(debian_url); );;
    alpine) ( mkdir -p $htdocs/$(alpine_dir); cd $htdocs/$(alpine_dir); wget --no-clobber $(alpine_url); );;
esac
