#!/usr/bin/env bash
set -ueo pipefail
repo=$(pwd)
dist=~/.cache/netboot/dist
version=$1
arch=$2
user=$USER
serial=no
target=$3
doas $repo/scripts/mkboot.openbsd $repo $dist $version $arch $user $serial $target
